### ISSUE TITLE
Modifier Écran pour Match

### ISSUE THREAD

**Issue by laguiche** [CRLG/LABOTBOX#3]
Entre autre:
Ajouter bouton de reconnexion avec info de connexion rs232 et messagerie

_Sent from my WIKO U FEEL PRIME using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by NicoFarmer** [comment]
Plus aucun problème de connexion RS232 depuis la mise en place de RobianPi et les évolutions Labotbox pour 2019. .
-> Ticket soldé
