### ISSUE TITLE
[QCustomPlot] Migration vers la dernière version 2.1.1 (06/11/2022)

### ISSUE THREAD

**Issue by NicoFarmer** [CRLG/LABOTBOX#78]
Mise à jour de la version de QCustomPlot pour bénéficier des évolutions (courbes polaires).
Besoin dans le cadre du développement du module LIDAR pour avoir une vue circulaire des obstacles.

Attention : impact sur le BasicModule Graph qui ne compile plus.
**Décision du 17/11/2023** : on migre QCustomPlot en V2.1.1 en mettant le BasicModule Graph en désactivant le module Graph temporairement.

**Comment by laguiche** [comment]
DataGraph est corrigé et réactivé. Aucun autre pb de compilation. @NicoFarmer a priori l'issue peut être fermée. :-)
